"""Build-37 array uploads must reach the GRCh38 ClinVar panel via liftover."""
import tempfile, os
from geneask.parsers import parse_file
from geneask.parsers.to_carried import carried_from_parse
from geneask.parsers.lift import lift_37_to_38


def test_lift_37_to_38_known_point():
    # a coordinate that lifts cleanly (APC region used in end-to-end validation):
    # hg19 5:112043375 -> hg38 5:112707678
    out = lift_37_to_38("5", 112043375)
    assert out is not None
    assert out[0] == "5" and out[1] == 112707678


def test_build37_upload_matches_hg38_panel():
    # panel is GRCh38 at 5-112707678-G-A; a build-37 upload sits at 5:112043375.
    # Without liftover this matches nothing; with it, it must produce a carried hit.
    panel = {"APC": {"variants": [
        {"variant_id": "5-112707678-G-A", "clinical_significance": "Pathogenic", "gold_stars": 2}]}}
    d = tempfile.mkdtemp(); p = os.path.join(d, "a.txt")
    open(p, "w").write("# This data file generated by 23andMe\n# Build 37\n"
                       "# rsid\tchromosome\tposition\tgenotype\n"
                       "rsX\t5\t112043375\tGA\n")
    parsed = parse_file(p)
    assert parsed.build == "37"
    carried = carried_from_parse(parsed, panel)
    assert any(c["variant_id"] == "5-112707678-G-A" for c in carried), \
        "build-37 upload failed to reach the GRCh38 panel via liftover"
    assert any("GRCh37" in n for n in parsed.notes)   # build handling surfaced
