"""Vendor genotype parser registry: auto-detect + normalized records + panel-anchor."""
import os, tempfile
from geneask.parsers import detect_parser, parse_file
from geneask.parsers.to_carried import carried_from_parse


def _w(txt):
    d = tempfile.mkdtemp()
    p = os.path.join(d, "f.txt")
    open(p, "w").write(txt)
    return p


ANC = ("#AncestryDNA raw data download\nrsid\tchromosome\tposition\tallele1\tallele2\n"
       "rs1\t1\t100\tA\tG\nrs2\t23\t200\t0\t0\n")   # rs2 = X, no-call
TAM = ("# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n"
       "rs1\t1\t100\tAG\ni700\tY\t200\tA\n")          # haploid Y
MYH = ('# MyHeritage\n"RSID","CHROMOSOME","POSITION","RESULT"\n"rs1","1","100","AG"\n')
LIV = ("# Living DNA customer genotype data\n# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAG\n")
MHG = ("# MyHappyGenes [TEMPUS]\nSNP Name\tChr\tPosition\tAllele1 - Forward\tAllele2 - Forward\n"
       "rs1\t1\t100\tA\tG\n")
FTD = 'RSID,CHROMOSOME,POSITION,RESULT\n"rs1","1","100","AG"\n'
FAM = ("# ftdna famfinder\nRSID\tCHROMOSOME\tPOSITION\tALLELE1\tALLELE2\nrs1\t1\t100\tA\tG\n")


def test_autodetect_vendor():
    cases = {ANC: "ancestrydna", TAM: "23andme", MYH: "myheritage",
             LIV: "livingdna", MHG: "myhappygenes", FTD: "ftdna", FAM: "ftdna"}
    for txt, name in cases.items():
        p = detect_parser(_w(txt))
        assert p is not None and p.name == name, f"{name}: got {p and p.name}"


def test_ancestry_normalization():
    r = parse_file(_w(ANC))
    assert r.source == "ancestrydna" and r.build == "37"
    assert r.records[0].chrom == "1" and r.records[0].allele1 == "A"
    assert r.records[1].chrom == "X" and r.records[1].is_nocall   # 23->X, 0/0 nocall
    assert r.n_nocall == 1


def test_23andme_haploid_and_build():
    r = parse_file(_w(TAM))
    hap = [x for x in r.records if x.rsid == "i700"][0]
    assert hap.chrom == "Y" and hap.allele1 == "A" and hap.allele2 == ""   # haploid


def test_myhappygenes_build_unknown():
    # header claims 37.1 but is really 38 -> build must be 'unknown' (don't trust header)
    assert parse_file(_w(MHG)).build == "unknown"


def test_panel_anchor_snv_only():
    # use a build-38 input so coordinates match the panel directly (no liftover),
    # isolating the SNV-only / indel-anchor-guard behaviour.
    b38 = ("# This data file generated by 23andMe\n# Build 38\n"
           "# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAG\n")
    panel = {"G": {"variants": [
        {"variant_id": "1-100-A-G", "clinical_significance": "Pathogenic", "gold_stars": 2},
        {"variant_id": "1-100-AT-A", "clinical_significance": "Pathogenic", "gold_stars": 2}]}}
    parsed = parse_file(_w(b38))            # rs1 at 1:100 carries A/G, build 38
    assert parsed.build == "38"
    carried = carried_from_parse(parsed, panel)
    vids = [c["variant_id"] for c in carried]
    assert "1-100-A-G" in vids              # SNV matched
    assert "1-100-AT-A" not in vids         # indel-anchor guard drops it
