"""23andMe raw export. TAB-delimited, 4 columns: rsid, chrom, pos, genotype
(concatenated, e.g. 'AG'). Detection: '# This data file generated by 23andMe' or
'23andme' in a comment. Build 36/37/38 from the header. No-call = '--'.
Haploid calls (X/Y/MT) appear as a single character. I-prefixed internal probe
IDs (i3000043) are passed through as the rsid.
"""
from __future__ import annotations
import re
from .base import GenotypeParser, GenotypeRecord, ParseResult, norm_chrom, norm_allele
from ._helpers import head_lines, data_rows


class TwentyThreeAndMeParser(GenotypeParser):
    name = "23andme"
    default_build = "37"

    def sniff(self, head: list[str]) -> bool:
        return any("23andme" in l.lower() for l in head[:10])

    def _build(self, head: list[str]) -> str:
        j = "\n".join(head).lower()
        m = re.search(r"build\s*(3[678])", j)
        return m.group(1) if m else self.default_build

    def parse(self, path: str) -> ParseResult:
        res = ParseResult(source=self.name, build=self._build(head_lines(path)))
        for f in data_rows(path, "\t"):
            if len(f) < 4 or f[0].lower() == "rsid":
                continue
            rsid, chrom, pos, geno = f[0], f[1], f[2], f[3].strip()
            try:
                p = int(pos)
            except ValueError:
                continue
            a1 = geno[0] if len(geno) >= 1 else ""
            a2 = geno[1] if len(geno) >= 2 else ""
            r = GenotypeRecord(rsid, norm_chrom(chrom), p, norm_allele(a1), norm_allele(a2))
            if r.is_nocall:
                res.n_nocall += 1
            res.records.append(r)
        return res
